export const WEATHERAPI_GET__READ = "WEATHERAPI_GET__READ"
export const WEATHERAPI_GET__READ_SUCCEEDED = "WEATHERAPI_GET__READ_SUCCEEDED"
export const WEATHERAPI_GET__READ_FAILED = "WEATHERAPI_GET__READ_FAILED"
