export const WEATHERAPI_GET__READ = "WEATHERAPI_GET__READ"
export const WEATHERAPI_GET__READ_SUCCEEDED = "WEATHERAPI_GET__READ_SUCCEEDED"
export const WEATHERAPI_GET__READ_FAILED = "WEATHERAPI_GET__READ_FAILED"
export const NEWPLUGINXXXX_GET__READ = "NEWPLUGINXXXX_GET__READ"
export const NEWPLUGINXXXX_GET__READ_SUCCEEDED =
  "NEWPLUGINXXXX_GET__READ_SUCCEEDED"
export const NEWPLUGINXXXX_GET__READ_FAILED = "NEWPLUGINXXXX_GET__READ_FAILED"
